experiment_name: 'chexpert_classifier'
phase: 'classification'
type: 'unimodal'

lightning:
    trainer:
       gpus: '0'
       max_epochs: 15
       distributed_backend: 'dp'
       gradient_clip_val: 0.25
       lr: 1e-4
       precision: 32
    checkpoint_callback:
        monitor: 'val_loss'
        dirpath: './data/ckpt'
        save_last: true 
        mode: min
        save_top_k: 1
    early_stopping_callback:
        monitor: 'val_loss'
        min_delta: 0.00
        patience: 10
        verbose: False
        mode: 'min'
    logger:
        logger_type: 'WandbLogger'
        save_dir: './data/'
        project: 'GLoRIA'

model: 
    vision:
        model_name: 'gloria_resnet50_ISIC_seed_65967'
        freeze_cnn: true
        pretrained: false
        num_targets: 8

data: 
    dataset: isic
    image:
        imsize: 384
    root: "/scratch/ssc10020/IndependentStudy/SLIP/dataset/ISIC/"
    
transforms: 
    norm: 'half'
    random_crop:
        crop_size: 384

train: 
    batch_size: 64
    num_workers: 16
    loss_fn: 
        type: CE
    optimizer: 
        name: 'Adam'
        weight_decay: 1e-6
    scheduler: 
        name: 'plateau'
        monitor: 'val_loss'
        interval: 'epoch'
        frequency: 3